name: itio_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  
  freezed_annotation: ^2.4.4
  gif_view: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_quill_test: ^11.0.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SBL_Hebrew
      fonts:
        - asset: assets/fonts/SBL_Hbrw.ttf
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Bold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
